name: OpenTofu Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  opentofu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set OpenTofu variables
        run: |
          echo "TF_VAR_project_id=${{ vars.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_region=${{ vars.GCP_REGION }}" >> $GITHUB_ENV
          echo "TF_VAR_zone=${{ vars.GCP_ZONE }}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.10.0"

      - name: OpenTofu Init
        env:
          GCS_BUCKET: ${{ vars.GCP_GCS_BUCKET }}
        run: |
          tofu init -upgrade \
            -backend-config="bucket=${GCS_BUCKET}" \
            -backend-config="prefix=${{ github.repository }}/opentofu/${{ github.ref_name }}"

      - name: OpenTofu Plan
        if: github.event_name == 'pull_request'
        run: tofu plan

      - name: OpenTofu Apply
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve